# Break comments to fit on the line
wrap_comments = true
# Maximum length of comments. No effect unlesswrap_comments = true.
comment_width = 100
# Replace uses of the try! macro by the ? shorthand
use_try_shorthand = true
# Reorder impl items. type and const are put first, then macros and methods
reorder_impl_items = true
# Use field initialize shorthand if possible
use_field_init_shorthand = true
# Convert #![doc] and #[doc] attributes to //! and /// doc comments
normalize_doc_attributes = true
# Replace strings of _ wildcards by a single .. in tuple patterns
condense_wildcard_suffixes = true
# Format code snippet included in doc comments.
format_code_in_doc_comments = true

# https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#overflow_delimited_expr
overflow_delimited_expr = true
# https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#StdExternalCrate%5C%3A
group_imports = "StdExternalCrate"
# https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#Crate%5C%3A
imports_granularity = "Crate"